### ISSUE TITLE
bug: go test fails

### ISSUE THREAD

**Issue by aodhgan** [Layr-Labs/eigenpod-proofs-generation#159]
running `go test` on `master` results in:
```
panic: open data/deneb_holesky_beacon_state_2227472.ssz: no such file or directory

goroutine 1 [running]:
github.com/Layr-Labs/eigenpod-proofs-generation_test.TestMain(0x140001b7cc0)
        /Users/aodhgan/eigenpod-proofs-generation/eigen_pod_proofs_test.go:37 +0x238
main.main()
        _testmain.go:63 +0x98
exit status 2
FAIL    github.com/Layr-Labs/eigenpod-proofs-generation 0.257s
```

since that test data file is not checked in

**Comment by aodhgan** [comment]
ah i see its being pulled in here: https://github.com/Layr-Labs/eigenpod-proofs-generation/blob/master/.github/workflows/go_test.yml#L27

is this something we could do in the Makefile as part of setup or add a `test` command
